version: '2'

services:
  kafka_monitor:
    image: istresearch/scrapy-cluster:kafka-monitor-dev
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - LOG_STDOUT=False
      - LOG_USE_JSON=True
    depends_on:
      - kafka-service
      - redis-service
    restart: always
  redis_monitor:
    image: istresearch/scrapy-cluster:redis-monitor-dev
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - LOG_STDOUT=False
      - LOG_USE_JSON=True
    depends_on:
      - kafka-service
      - redis-service
      - zookeeper-service
    restart: always
  crawler:
    image: istresearch/scrapy-cluster:crawler-dev
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - SC_LOG_STDOUT=False
      - SC_LOG_JSON=True
    depends_on:
      - kafka-service
      - redis-service
      - zookeeper-service
    restart: always
  rest:
    image: istresearch/scrapy-cluster:rest-dev
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - LOG_STDOUT=False
      - LOG_USE_JSON=True
    depends_on:
      - kafka-service
      - redis-service
    restart: always
    ports:
      - "5343:5343"
  redis-service:
    image: redis
    ports:
      - "6379"
    restart: always
  zookeeper-service:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka-service:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper-service
    restart: always

volumes:
  logs: