apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-dp
  namespace: scrapy-cluster
spec:
  replicas: 1
  selector:
    app: kafka-dp
  template:
    metadata:
      labels:
        app: kafka-dp
    spec:
      containers:
      - name: kafka-dp
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.10.7
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-sv:2181
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: kafka2
#  namespace: scrapy-cluster
#spec:
#  replicas: 1
#  selector:
#    app: kafka2
#  template:
#    metadata:
#      labels:
#        app: kafka2
#    spec:
#      containers:
#      - name: kafka2
#        image: wurstmeister/kafka
#        ports:
#        - containerPort: 9092
#        env:
#        - name: KAFKA_BROKER_ID
#          value: "2"
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: 10.101.183.68
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: zoo1:2181,zoo2:2181,zoo3:2181
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: kafka3
#  namespace: scrapy-cluster
#spec:
#  replicas: 1
#  selector:
#    app: kafka3
#  template:
#    metadata:
#      labels:
#        app: kafka3
#    spec:
#      containers:
#      - name: kafka3
#        image: wurstmeister/kafka
#        ports:
#        - containerPort: 9092
#        env:
#        - name: KAFKA_BROKER_ID
#          value: "3"
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: 10.106.138.98
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: zoo1:2181,zoo2:2181,zoo3:2181
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: kafka4
#  namespace: scrapy-cluster
#spec:
#  replicas: 1
#  selector:
#    app: kafka4
#  template:
#    metadata:
#      labels:
#        app: kafka4
#    spec:
#      containers:
#      - name: kafka4
#        image: wurstmeister/kafka
#        ports:
#        - containerPort: 9092
#        env:
#        - name: KAFKA_BROKER_ID
#          value: "4"
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: 10.108.244.43
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: zoo1:2181,zoo2:2181,zoo3:2181
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: kafka5
#  namespace: scrapy-cluster
#spec:
#  replicas: 1
#  selector:
#    app: kafka5
#  template:
#    metadata:
#      labels:
#        app: kafka5
#    spec:
#      containers:
#      - name: kafka5
#        image: wurstmeister/kafka
#        ports:
#        - containerPort: 9092
#        env:
#        - name: KAFKA_BROKER_ID
#          value: "5"
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: 10.100.84.154
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: zoo1:2181,zoo2:2181,zoo3:2181


