apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
