apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - image: istresearch/scrapy-cluster:rest-1.2.2
        imagePullPolicy: IfNotPresent
        name: rest
        ports:
        - containerPort: 5343