apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-dp
  namespace: scrapy-cluster
spec:
  replicas: 1
  selector:
    app: zookeeper-dp
  template:
    metadata:
      labels:
        app: zookeeper-dp
    spec:
      containers:
      - name: zookeeper-dp
        image: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "all"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-sv


