apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: kafka-pv
  namespace: scrapy-cluster
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/run/docker.sock
status: {}
