apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-0
  namespace: scrapy-cluster
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/ubuntu/Working/kafka_root/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-1
  namespace: scrapy-cluster
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/ubuntu/Working/kafka_root/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-2
  namespace: scrapy-cluster
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/ubuntu/Working/kafka_root/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-pc