apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181,zookeeper-service2:2181,zookeeper-service3:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.104.87.5 # kafka-service ClusterIP
        - name: KAFKA_BROKER_ID
          value: "1"
        name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka2
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - env:
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181,zookeeper-service2:2181,zookeeper-service3:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.103.40.229 # kafka-service ClusterIP
        - name: KAFKA_BROKER_ID
          value: "2"
        name: kafka2
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka3
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - env:
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181,zookeeper-service2:2181,zookeeper-service3:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.102.181.81 # kafka-service ClusterIP
        - name: KAFKA_BROKER_ID
          value: "3"
        name: kafka3
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092


