apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: scrapy-cluster
spec:
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka

