apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper2
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper2
    spec:
      containers:
      - image: zookeeper
        imagePullPolicy: IfNotPresent
        name: zookeeper2
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper3
  namespace: scrapy-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper3
    spec:
      containers:
      - image: zookeeper
        imagePullPolicy: IfNotPresent
        name: zookeeper3
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper2
        - name: ZOOKEEPER_SERVER_3
          value: zookeeper3
