apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: scrapy-cluster
spec:
  ports:
  - name: port-2181
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: port-2888
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: port-3888
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service2
  namespace: scrapy-cluster
spec:
  ports:
  - name: port-2181
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: port-2888
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: port-3888
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service3
  namespace: scrapy-cluster
spec:
  ports:
  - name: port-2181
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: port-2888
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: port-3888
    port: 3888
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper3