apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: scrapy-cluster
spec:
  selector:
    matchLabels:
      app: zookeeper
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        role: master
        tier: backend
    spec:
      containers:
      - image: zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
